name: Deploy Backend and Frontend to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "walicki"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: ./backend

  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install dependencies
        working-directory: ./frontend/construction-company-ms
        run: npm install
      - name: Build Frontend
        working-directory: ./frontend/construction-company-ms
        run: npm run build
      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ccmsystems"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: ./frontend/construction-company-ms
